### ISSUE TITLE
[Mechanics] too many blue lines

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#14]
Currently sketches have too many blue undefined lines. All lines should be black and fully defined. This is important because when changes are required, all sketch dimensions are pre-determined and funky stuff can not happen. If lines are blue, any dimension change can have unforeseen consequences to the component.

Some examples:

![image](https://user-images.githubusercontent.com/5435954/192094577-999e5f1a-0f56-44f9-a1cd-c5993f0e8f40.png)
![image](https://user-images.githubusercontent.com/5435954/192094620-5a680195-e1cc-46d2-9aae-eaf0479bb86f.png)
![image](https://user-images.githubusercontent.com/5435954/192094646-4da15e81-2c63-4d32-9e50-3c816593e682.png)

**Comment by marcanderetti** [comment]
Everything should be fixed now

**Comment by Akustav** [comment]
I think everything is not fixed. Some things I found:

![image](https://user-images.githubusercontent.com/5435954/193411414-40615901-f9a4-4c9c-ac9c-a4a478e06e3f.png)
![image](https://user-images.githubusercontent.com/5435954/193411421-3be246c0-dcb3-4370-8df4-aec80efa17d0.png)

Overall I also think you have way to many sketches per component so it is hard to understand at times what is in scope for the component.

**Comment by marcanderetti** [comment]
Will it really be a problem?

**Comment by Akustav** [comment]
Yes. When I moved them so did the slots. For future components any wrong drag or sketch change can create a cascade of weird sketch transformations.
